[project]
name = "photochomper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.1",
    "pillow>=11.3.0",
    "rich>=14.1.0",
]
